# Generated by Django 4.2.3 on 2023-11-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0002_navbarrightcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbarrighmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Medya İcon Uzantısı')),
                ('link', models.URLField()),
            ],
        ),
    ]
