# Generated by Django 4.2.3 on 2023-11-27 21:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0004_headercarousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexsectionone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SecondSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='subsection_images/')),
                ('sub_title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.indexsectionone')),
            ],
        ),
        migrations.CreateModel(
            name='FirstSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image_1', models.ImageField(upload_to='indexsectiononecarousel_images/')),
                ('carousel_image_2', models.ImageField(blank=True, null=True, upload_to='indexsectiononecarousel_images/')),
                ('carousel_image_3', models.ImageField(blank=True, null=True, upload_to='indexsectiononecarousel_images/')),
                ('carousel_image_4', models.ImageField(blank=True, null=True, upload_to='indexsectiononecarousel_images/')),
                ('sub_title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.indexsectionone')),
            ],
        ),
    ]
