# Generated by Django 4.2.3 on 2023-11-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0005_indexsectionone_secondsubsection_firstsubsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstsubsection',
            name='carousel_image_1',
        ),
        migrations.RemoveField(
            model_name='firstsubsection',
            name='carousel_image_2',
        ),
        migrations.RemoveField(
            model_name='firstsubsection',
            name='carousel_image_3',
        ),
        migrations.RemoveField(
            model_name='firstsubsection',
            name='carousel_image_4',
        ),
        migrations.AddField(
            model_name='firstsubsection',
            name='carousel_images',
            field=models.ImageField(blank=True, null=True, upload_to='indexsectiononecarousel_images/'),
        ),
    ]
