# Generated by Django 4.2.3 on 2023-11-28 09:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0007_remove_firstsubsection_carousel_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexsectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Anasayfa - Section-3',
                'verbose_name_plural': 'Anasayfa Section-3',
            },
        ),
        migrations.AlterModelOptions(
            name='headercarousel',
            options={'verbose_name': 'Anasayfa Carousel', 'verbose_name_plural': 'Anasayfa Carousel'},
        ),
        migrations.AlterModelOptions(
            name='indexsectionone',
            options={'verbose_name': 'Anasayfa - Section-1', 'verbose_name_plural': 'Anasayfa Section-1'},
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': 'Navbar', 'verbose_name_plural': 'Navbar'},
        ),
        migrations.AlterModelOptions(
            name='navbarrighmedia',
            options={'verbose_name': 'Navbar Sağ Sosyal Medyalar', 'verbose_name_plural': 'Navbar Sağ Sosyal Medyalar'},
        ),
        migrations.AlterModelOptions(
            name='navbarrightcontact',
            options={'verbose_name': 'Navbar Sağ Kontak Alanı (Email-Telefon)', 'verbose_name_plural': 'Navbar Sağ Kontak Alanı (Email-Telefon)'},
        ),
        migrations.CreateModel(
            name='FirstSubSectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(null=True, upload_to='indexsectionthreecarousel_images/')),
                ('sub_title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.indexsectionthree')),
            ],
        ),
    ]
