# Generated by Django 4.2.3 on 2023-11-28 11:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0009_indexsectionfour_firstsubsectionfour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexsectionfive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='indexsectionfive_images/')),
            ],
            options={
                'verbose_name': 'Anasayfa - Section-5',
                'verbose_name_plural': 'Anasayfa Section-5',
            },
        ),
        migrations.CreateModel(
            name='FirstSubSectionFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField()),
                ('answer', ckeditor.fields.RichTextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.indexsectionfive')),
            ],
        ),
    ]
