# Generated by Django 4.2.3 on 2023-11-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0011_indexsectionsix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexsectionsix',
            name='title',
        ),
    ]
