# Generated by Django 4.2.3 on 2023-11-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0014_footersubsection_socialmedia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersubsection',
            name='socialmedia',
        ),
        migrations.RemoveField(
            model_name='footersubsection',
            name='socialmedia_link',
        ),
        migrations.CreateModel(
            name='FooterSupSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialmedia', models.CharField(max_length=50, null=True, verbose_name='Sosyal Medya İcon Uzantısı (Örn: fa fa-github)')),
                ('socialmedia_link', models.URLField(null=True, verbose_name='Sosyal Medya İtemi Linki')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.footer')),
            ],
        ),
    ]
