# Generated by Django 4.2.3 on 2023-11-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0015_remove_footersubsection_socialmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='adress',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
