# Generated by Django 4.2.3 on 2023-11-29 12:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0016_footer_adress_footer_email_footer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectssheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('about', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Projelerim Sayfası',
                'verbose_name_plural': 'Projelerim Sayfası',
            },
        ),
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=500)),
                ('site_img', models.ImageField(upload_to='Projectscard_images/')),
                ('site_img_logo', models.ImageField(upload_to='Projectscard_images/')),
                ('site_url', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.projectssheet')),
            ],
        ),
    ]
