# Generated by Django 4.2.3 on 2023-11-29 13:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0017_projectssheet_projectcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('about', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Hakkımda Sayfası',
                'verbose_name_plural': 'Hakkımda Sayfası',
            },
        ),
        migrations.CreateModel(
            name='Myskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=500)),
                ('skill_about', ckeditor.fields.RichTextField()),
                ('skill_img1', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('skill_img2', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('skill_img3', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('skill_img4', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('skill_img5', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('skill_img6', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('skill_img7', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('skill_img8', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('skill_img9', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('skill_img10', models.ImageField(blank=True, null=True, upload_to='Skill_images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.aboutsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_title', models.CharField(max_length=500)),
                ('cert_about', ckeditor.fields.RichTextField()),
                ('cert_img1', models.ImageField(blank=True, null=True, upload_to='Certificate_images/')),
                ('cert_img2', models.ImageField(blank=True, null=True, upload_to='Certificate_images/')),
                ('cert_img3', models.ImageField(blank=True, null=True, upload_to='Certificate_images/')),
                ('cert_img4', models.ImageField(blank=True, null=True, upload_to='Certificate_images/')),
                ('cert_img5', models.ImageField(blank=True, null=True, upload_to='Certificate_images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.aboutsheet')),
            ],
        ),
    ]
