# Generated by Django 4.2.3 on 2023-11-29 20:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0019_aboutsheet_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('title', models.CharField(max_length=250)),
                ('text', ckeditor.fields.RichTextField()),
                ('subject', models.CharField(max_length=250)),
                ('subject_icon', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
