# Generated by Django 4.2.3 on 2023-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0020_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
