# Generated by Django 4.2.3 on 2023-12-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0021_navbar_title_en_navbar_title_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercarousel',
            name='about_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='headercarousel',
            name='about_tr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='headercarousel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headercarousel',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headercarousel',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='headercarousel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
