# Generated by Django 4.2.3 on 2023-12-03 17:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0022_headercarousel_about_en_headercarousel_about_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsubsection',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsection',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsection',
            name='sub_title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsection',
            name='sub_title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionone',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionone',
            name='title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='secondsubsection',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='secondsubsection',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='secondsubsection',
            name='sub_title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='secondsubsection',
            name='sub_title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsection',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsection',
            name='sub_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indexsectionone',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='secondsubsection',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='secondsubsection',
            name='image',
            field=models.ImageField(null=True, upload_to='subsection_images/'),
        ),
        migrations.AlterField(
            model_name='secondsubsection',
            name='sub_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
