# Generated by Django 4.2.3 on 2023-12-03 18:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0023_firstsubsection_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsubsectionthree',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionthree',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionthree',
            name='sub_title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionthree',
            name='sub_title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionthree',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionthree',
            name='title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsectionthree',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsectionthree',
            name='sub_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indexsectionthree',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
