# Generated by Django 4.2.3 on 2023-12-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0024_firstsubsectionthree_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsectionthree',
            name='buttonText',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionthree',
            name='buttonText_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionthree',
            name='buttonText_tr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
