# Generated by Django 4.2.3 on 2023-12-03 20:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0025_indexsectionthree_buttontext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstsubsectionfour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='firstsubsectionfour',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='analysisTitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='analysisTitle_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='analysisTitle_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='analysis_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='analysis_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='codingTitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='codingTitle_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='codingTitle_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='coding_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='coding_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='designTitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='designTitle_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='designTitle_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='design_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='design_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='maintenance_support_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='maintenance_support_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='maintenance_support_title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='maintenance_support_title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='maintenance_support_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='sueTitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='sueTitle_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='sueTitle_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='sue_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='sue_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='testingTitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='testingTitle_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='testingTitle_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='testing_release_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfour',
            name='testing_release_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='buttonText',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='buttonText_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='buttonText_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='sub_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='sub_title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='sub_title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfour',
            name='title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsectionfour',
            name='analysis',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsectionfour',
            name='coding',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsectionfour',
            name='design',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsectionfour',
            name='maintenance_support',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsectionfour',
            name='sue',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='firstsubsectionfour',
            name='testing_release',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='indexsectionfour',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
