# Generated by Django 4.2.3 on 2023-12-03 21:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0026_remove_firstsubsectionfour_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsubsectionfive',
            name='answer_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfive',
            name='answer_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfive',
            name='question_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='firstsubsectionfive',
            name='question_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfive',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfive',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfive',
            name='sub_title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfive',
            name='sub_title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfive',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexsectionfive',
            name='title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
