# Generated by Django 4.2.3 on 2023-12-03 21:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0027_firstsubsectionfive_answer_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsectionsix',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='indexsectionsix',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='indexsectionsix',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
