# Generated by Django 4.2.3 on 2023-12-03 22:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0028_indexsectionsix_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='titleOne',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='titleOne_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='titleOne_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='titleThree',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='titleThree_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='titleThree_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='titleTwo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='titleTwo_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='titleTwo_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footersubsection',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Menü İtemi'),
        ),
        migrations.AddField(
            model_name='footersubsection',
            name='title_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Menü İtemi'),
        ),
        migrations.AddField(
            model_name='footersubsection',
            name='url_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Menü İtemi Linki'),
        ),
        migrations.AddField(
            model_name='footersubsection',
            name='url_tr',
            field=models.CharField(max_length=500, null=True, verbose_name='Menü İtemi Linki'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
