# Generated by Django 4.2.3 on 2023-12-03 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0030_indexpagemap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpagemap',
            name='href_id',
        ),
        migrations.RemoveField(
            model_name='indexpagemap',
            name='href_title',
        ),
        migrations.RemoveField(
            model_name='indexpagemap',
            name='href_title_en',
        ),
        migrations.RemoveField(
            model_name='indexpagemap',
            name='href_title_tr',
        ),
        migrations.CreateModel(
            name='IndexPageMapSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href_id', models.CharField(max_length=250, null=True)),
                ('href_title', models.CharField(max_length=250, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.indexpagemap')),
            ],
        ),
    ]
