# Generated by Django 4.2.3 on 2023-12-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0031_remove_indexpagemap_href_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemapsubsection',
            name='href_title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indexpagemapsubsection',
            name='href_title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
