# Generated by Django 4.2.3 on 2023-12-04 14:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0032_indexpagemapsubsection_href_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcard',
            name='buttonText',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='about_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='about_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='breadcrumbOne',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='breadcrumbOneUrl',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='breadcrumbOne_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='breadcrumbOne_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='breadcrumbTwo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='breadcrumbTwo_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='breadcrumbTwo_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='headTitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='headTitle_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='headTitle_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectssheet',
            name='title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='site_img',
            field=models.ImageField(null=True, upload_to='Projectscard_images/'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='site_img_logo',
            field=models.ImageField(null=True, upload_to='Projectscard_images/'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='site_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='site_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='projectssheet',
            name='about',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='projectssheet',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
