# Generated by Django 4.2.3 on 2023-12-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0033_projectcard_buttontext_projectssheet_about_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectssheet',
            name='breadcrumbOneUrl',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
