# Generated by Django 4.2.3 on 2023-12-04 15:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0035_projectcard_buttontext_en_projectcard_buttontext_tr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsheet',
            name='about',
        ),
        migrations.RemoveField(
            model_name='aboutsheet',
            name='img',
        ),
        migrations.RemoveField(
            model_name='aboutsheet',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='breadcrumbOne',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='breadcrumbOneUrl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='breadcrumbOne_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='breadcrumbOne_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='breadcrumbTwo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='breadcrumbTwo_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='breadcrumbTwo_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='headTitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='headTitle_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutsheet',
            name='headTitle_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_about_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_about_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_title_tr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='myskills',
            name='skill_about_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='myskills',
            name='skill_about_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='myskills',
            name='skill_title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='myskills',
            name='skill_title_tr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_about',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='myskills',
            name='skill_about',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='myskills',
            name='skill_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('title_tr', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('about', ckeditor.fields.RichTextField(null=True)),
                ('about_tr', ckeditor.fields.RichTextField(null=True)),
                ('about_en', ckeditor.fields.RichTextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='about_images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.aboutsheet')),
            ],
            options={
                'verbose_name': 'Hakkımda Sayfası',
                'verbose_name_plural': 'Hakkımda Sayfası',
            },
        ),
    ]
