# Generated by Django 4.2.3 on 2023-12-04 18:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0036_remove_aboutsheet_about_remove_aboutsheet_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumbOne', models.CharField(max_length=250, null=True)),
                ('breadcrumbOne_tr', models.CharField(max_length=250, null=True)),
                ('breadcrumbOne_en', models.CharField(max_length=250, null=True)),
                ('breadcrumbOneUrl', models.CharField(max_length=250, null=True)),
                ('breadcrumbTwo', models.CharField(max_length=250, null=True)),
                ('breadcrumbTwo_tr', models.CharField(max_length=250, null=True)),
                ('breadcrumbTwo_en', models.CharField(max_length=250, null=True)),
                ('headTitle', models.CharField(max_length=250, null=True)),
                ('headTitle_tr', models.CharField(max_length=250, null=True)),
                ('headTitle_en', models.CharField(max_length=250, null=True)),
                ('subtitle', models.CharField(max_length=250, null=True)),
                ('subtitle_tr', models.CharField(max_length=250, null=True)),
                ('subtitle_en', models.CharField(max_length=250, null=True)),
                ('about', ckeditor.fields.RichTextField(null=True)),
                ('about_tr', ckeditor.fields.RichTextField(null=True)),
                ('about_en', ckeditor.fields.RichTextField(null=True)),
                ('buttonText', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'İletişim Sayfası',
                'verbose_name_plural': 'İletişim Sayfası',
            },
        ),
    ]
