# Generated by Django 4.2.3 on 2023-12-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0037_contactsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsheet',
            name='buttonText_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contactsheet',
            name='buttonText_tr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
