# Generated by Django 4.2.3 on 2023-12-04 19:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0038_contactsheet_buttontext_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumbOne', models.CharField(max_length=250, null=True)),
                ('breadcrumbOne_tr', models.CharField(max_length=250, null=True)),
                ('breadcrumbOne_en', models.CharField(max_length=250, null=True)),
                ('breadcrumbOneUrl', models.CharField(max_length=250, null=True)),
                ('breadcrumbTwo', models.CharField(max_length=250, null=True)),
                ('breadcrumbTwo_tr', models.CharField(max_length=250, null=True)),
                ('breadcrumbTwo_en', models.CharField(max_length=250, null=True)),
                ('headTitle', models.CharField(max_length=250, null=True)),
                ('headTitle_tr', models.CharField(max_length=250, null=True)),
                ('headTitle_en', models.CharField(max_length=250, null=True)),
                ('subtitle', models.CharField(max_length=250, null=True)),
                ('subtitle_tr', models.CharField(max_length=250, null=True)),
                ('subtitle_en', models.CharField(max_length=250, null=True)),
                ('about', ckeditor.fields.RichTextField(null=True)),
                ('about_tr', ckeditor.fields.RichTextField(null=True)),
                ('about_en', ckeditor.fields.RichTextField(null=True)),
                ('authorsub', models.CharField(max_length=250)),
                ('authorsub_tr', models.CharField(max_length=250, null=True)),
                ('authorsub_en', models.CharField(max_length=250, null=True)),
                ('buttonText', models.CharField(max_length=250, null=True)),
                ('buttonText_tr', models.CharField(max_length=250, null=True)),
                ('buttonText_en', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subject_icon',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbOne',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbOneUrl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbOne_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbOne_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbThree',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbThree_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbThree_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbTwo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbTwoUrl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbTwo_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='breadcrumbTwo_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='buttonText',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='buttonText_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='buttonText_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='headTitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='headTitle_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='headTitle_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='BlogWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='blog_images/')),
                ('title', models.CharField(max_length=250, null=True)),
                ('title_tr', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('text_tr', ckeditor.fields.RichTextField(null=True)),
                ('text_en', ckeditor.fields.RichTextField(null=True)),
                ('subject', models.CharField(max_length=250, null=True)),
                ('subject_tr', models.CharField(max_length=250, null=True)),
                ('subject_en', models.CharField(max_length=250, null=True)),
                ('subject_icon', models.CharField(max_length=250, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsiteapp.blog')),
            ],
        ),
    ]
