# Generated by Django 4.2.3 on 2023-12-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0039_bloglist_remove_blog_author_remove_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='buttonText_subject_all',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bloglist',
            name='buttonText_subject_all_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bloglist',
            name='buttonText_subject_all_tr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
