# Generated by Django 4.2.3 on 2023-12-04 20:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0040_bloglist_buttontext_subject_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thankyou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('title_tr', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('text_tr', ckeditor.fields.RichTextField(null=True)),
                ('text_en', ckeditor.fields.RichTextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='thankyou_images/')),
            ],
        ),
    ]
