# Generated by Django 4.2.3 on 2023-12-08 16:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0041_thankyou'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcard',
            name='site_about',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='site_about_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='site_about_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
