# Generated by Django 4.2.3 on 2023-12-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0046_remove_person_cvhead2_remove_person_cvhead2_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myskills',
            name='section',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Myskills',
        ),
    ]
