# Generated by Django 4.2.3 on 2023-12-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsiteapp', '0047_remove_myskills_section_delete_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='socialmediaIcon3',
        ),
        migrations.RemoveField(
            model_name='person',
            name='socialmediaIcon3_url',
        ),
    ]
